[project]
name = "iqm-quantum-school-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "iqm-client>=32.1.1,<33.0",
    "qrisp[iqm]>=0.7.14",
]
